version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: Any CPU
branches:
  only:
  - master
build_script:
- ps: .\build.ps1
artifacts:
- path: artifacts\**\*.nupkg
notifications:
- provider: Email
  to:
  - christian.junk@geomatics.io
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false